---
scalar_key: "A Scalar Value"
boolean: true
integer: 42
sequence:
    - act: "idx"
      title: "Welcome"
      html: "public/welcome.html"
    - act: "reg"
      title: "Register"
      html: "public/register.html"
---
actions:
  - noop:
    - preconditions: none
    - postconditions: none
  - move:
    - preconditions: none
    - postconditions: none
  - dig:
    - preconditions: none
    - postconditions: none
materials: none
objects: none
effects: none
events: none
skills: none
areas:
  buildings: none
  zones: none
reactions:
  - name: reaction1
    location: location1
    skills:
      - skill1: level1
      - skill2: level2
    reagents:
      - reagent1: amount1
      - reagent2: amount2
    products:
      - product1: amount3
      - product2: amount4