:- dynamic celda/3.
max_row(5).
max_column(5).
celda([0,0],obs,-).
celda([0,1],obs,-).
celda([0,2],obs,-).
celda([0,3],obs,-).
celda([0,4],obs,-).
celda([0,5],obs,-).
celda([1,0],obs,-).
celda([1,1],alf,sucio).
celda([1,2],alf,sucio).
celda([1,3],alf,limpio).
celda([1,4],bal,sucio).
celda([1,5],obs,-).
celda([2,0],obs,-).
celda([2,1],obs,-).
celda([2,2],alf,limpio).
celda([2,3],alf,limpio).
celda([2,4],alf,limpio).
celda([2,5],obs,-).
celda([3,0],obs,-).
celda([3,1],alf,limpio).
celda([3,2],alf,limpio).
celda([3,3],home,-).
celda([3,4],alf,limpio).
celda([3,5],obs,-).
celda([4,0],obs,-).
celda([4,1],alf,limpio).
celda([4,2],bal,sucio).
celda([4,3],alf,limpio).
celda([4,4],obs,-).
celda([4,5],obs,-).
celda([5,0],obs,-).
celda([5,1],obs,-).
celda([5,2],obs,-).
celda([5,3],obs,-).
celda([5,4],obs,-).
celda([5,5],obs,-).
