---
scenarios:
  - name: basic
    global_env_kind: SquareGrid
    local_env_kind: SquareGrid
    starting_units:
      - Reactive:
          id: 1
          name: AgentOne
      - Reactive:
          id: 2
          name: AgentTwo
      - Reactive:
          id: 3
          name: AgentThree
  - name: dwarf_fortress
    global_env_kind: SquareGrid
    local_env_kind: VoxelGrid
  - name: advanced
    global_env_kind: GeodesicGrid
    local_env_kind: VoxelGrid
