[package]
name = "mmass"
version = "0.1.0"
authors = ["Iñaki Garay <igarai@gmail.com>"]

[dependencies]
env_logger = "0.5.3"
log = "0.4.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
rand = "0.4"

